version: '3'

services:
  server:
    container_name: casmm-server-dev
    # image: strapi/strapi
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    environment: 
      - DATABASE_HOST=db
    ports:
      - 1337:1337
    volumes:
      # - ./server:/srv/app
      - ./server:/usr/src/app
      - casmm-client-build:/usr/src/app/public/client
    depends_on:
      - db
      - compile_queue
  compile:
    container_name: casmm-compile-dev
    build: ./compile
    restart: always
    depends_on:
      - compile_queue
  db:
    container_name: casmm-db-dev
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENVIRONMENT: development
      DATABASE_URL: strapi
      SCRIPT_PATH: /docker-entrypoint-initdb.d
  compile_queue:
    container_name: casmm-compile_queue-dev
    image: redis
    restart: always
  
  client:
    container_name: casmm-client-dev
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      - casmm-client-build:/app/client/build
    depends_on:
      - server
    command: yarn start

volumes:
  casmm-client-build: